version: '3.1'
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: on-failure
  db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: db-57xsl
      MYSQL_DATABASE: example
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
    - 3000:3000
    depends_on:
      - backend