name: Pipeline
on: push
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
      - name: run containers
      - run: | 
          docker compose up -d
          docker ps
          docker images
      - name: Run tests
      - run: |
          docker exec react-java0mysql-frontend-1 curl localhost:3000
          docker exec react-java0mysql-backend-1 curl localhost:8080
        
