name: Pipeline
on: push
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
          
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
      - name: run containers
        run: | 
          docker compose up -d
          docker ps
          docker images
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: gilni/java-frontend:latest
        
